version: "3.9"

services:
  web:
    build: .
    container_name: online_cinema_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000

  celery:
    build: .
    container_name: online_cinema_celery
    command: celery -A src.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  beat:
    build: .
    container_name: online_cinema_beat
    command: celery -A src.celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: online_cinema_redis
    ports:
      - "6379:6379"
